clean: true
module: HTTP
author: Swift Server APIs
author_url: https://swift.org/server-apis/
github_url: https://github.com/paulofaria/http-proposal
swift_version: 3.1
xcodebuild_arguments:
  - -scheme
  - HTTP

custom_categories:
  - name: HTTP Version
    children:
    - HTTPVersion

  - name: HTTP Headers
    children:
    - HTTPHeaders
    
  - name: HTTP Request
    children:
    - HTTPRequest
    - HTTPMethod

  - name: HTTP Response
    children:
    - HTTPResponse
    - HTTPStatus
